'use client';

import { useRouter } from 'next/navigation';
import { useAuth } from '../components/AuthProvider';
import styles from '../styles/support.module.css';

export default function TermsPage() {
    const router = useRouter();
    const { user } = useAuth();

    return (
        <div className={styles.container}>
            <header className={styles.header}>
                <img 
                    src="/gradlae-logo.png" 
                    alt="Gradlae" 
                    className="brandLogo" 
                    onClick={() => router.push(user ? '/dashboard' : '/')} 
                    style={{ cursor: 'pointer' }} 
                />
                <button className={styles.backBtn} onClick={() => router.push('/')}>
                    Back to Home
                </button>
            </header>

            <main className={styles.main}>
                <div className={styles.contentCard}>
                    <h1>Terms &amp; Conditions</h1>
                    <p className={styles.subtitle}>Last updated: January 4, 2026</p>

                    <div className={styles.privacyContent}>
                        <h2>1. Acceptance of Terms</h2>
                        <p>
                            By accessing and using Gradlae, you agree to comply with and be bound by these Terms &amp; Conditions. If you do not agree to these terms, please do not use our services.
                        </p>

                        <h2>2. Pacing &amp; Placements</h2>
                        <p>
                            Pacing recommendations and batch placements are generated by our automated algorithm based on transcripts and quiz assessments. While these tools aim for optimal pacing, final enrollment decisions are subject to university guidelines and academic advisor approval.
                        </p>

                        <h2>3. User Responsibilities</h2>
                        <p>
                            You agree to provide true, accurate, and complete information when uploading transcripts or completing academic quizzes. Any attempts to manipulate scores, falsify transcript records, or engage in academic dishonesty will result in immediate termination of account access.
                        </p>

                        <h2>4. Stripe Mentoring Payments</h2>
                        <p>
                            Mentoring and tutoring slots purchased via our Stripe checkout flow are subject to scheduling availability. Cancellations must be made at least 24 hours prior to the scheduled slot to qualify for rescheduling. Single sessions and session passes are non-refundable.
                        </p>

                        <h2>5. Limitation of Liability</h2>
                        <p>
                            Gradlae shall not be held liable for any direct or indirect consequences arising from academic placement recommendations, including but not limited to course grades, scheduling delays, or graduation timing changes.
                        </p>

                        <h2>6. Changes to Terms</h2>
                        <p>
                            We reserve the right to modify these terms at any time. Your continued use of the platform following the posting of changes constitutes your acceptance of the updated terms.
                        </p>

                        <h2>7. Contact</h2>
                        <p>
                            For inquiries regarding our Terms of Service, please contact support at support@merse.com.
                        </p>
                    </div>
                </div>
            </main>
        </div>
    );
}
